#include <iostream>
#include <iomanip>
#include <fstream>
#include <chrono>
#include <string>
#include "parser.hpp"
#include "octree.hpp"
using namespace std;

static void printUsage(const char* programName) {
    cerr << "Penggunaan: " << programName << " <input.obj> <kedalamanMaks>\n";
    cerr << "  input.obj      : path ke file model 3D\n";
    cerr << "  kedalamanMaks  : kedalaman octree (bilangan bulat >= 1, disarankan 4-8)\n";
}

static void printReport(long long voxelCount, const OctreeStats& stats,
                        double elapsedSeconds, const string& outputPath) {
    long long vertexCount = voxelCount * 8;
    long long faceCount   = voxelCount * 12;

    cout << "\n";
    cout << "Banyaknya voxel yang terbentuk   : " << voxelCount  << "\n";
    cout << "Banyaknya vertex yang terbentuk  : " << vertexCount << "\n";
    cout << "Banyaknya faces yang terbentuk   : " << faceCount   << "\n";
    cout << "Kedalaman octree                 : " << stats.maxDepth << "\n";

    cout << "\nStatistik node octree yang terbentuk:\n";
    for (int d = 1; d <= stats.maxDepth; d++) {
        cout << d << " : " << stats.nodeCount[d] << "\n";
    }

    cout << "\nStatistik node yang tidak perlu ditelusuri:\n";
    for (int d = 1; d <= stats.maxDepth; d++) {
        cout << d << " : " << stats.prunedCount[d] << "\n";
    }

    cout << "\nLama waktu program berjalan      : " << fixed << setprecision(4)
         << elapsedSeconds << " s\n";
    cout << "Path file .obj disimpan          : " << outputPath << "\n\n";
}

int main(int argc, char* argv[]) {
    if (argc != 3) {
        printUsage(argv[0]);
        return 1;
    }

    string inputPath = argv[1];
    int maxDepth;

    try {
        string depthStr = argv[2];
        size_t processed;
        maxDepth = stoi(depthStr, &processed);
        if (processed != depthStr.size()) throw invalid_argument("trailing chars");
    } catch (...) {
        cerr << "Error: kedalamanMaks harus berupa bilangan bulat positif\n";
        printUsage(argv[0]);
        return 1;
    }

    if (maxDepth < 1 || maxDepth > 20) {
        cerr << "Error: kedalamanMaks harus antara 1 dan 20\n";
        return 1;
    }

    vector<Vec3> vertices;
    vector<Face> faces;
    Box root;

    if (!loadOBJRoot(inputPath, vertices, faces, root)) {
        return 1;
    }

    cout << "Berhasil membaca " << vertices.size() << " vertex dan "
         << faces.size() << " face.\n";
    cout << "Membangun octree pada kedalaman " << maxDepth << "...\n";

    root = transformBoundingBox(root);

    string outputPath = generateOutputPath(inputPath);
    ofstream out(outputPath);
    if (!out.is_open()) {
        cerr << "Error: tidak dapat membuat file output '" << outputPath << "'\n";
        return 1;
    }
    out << "# Voxelized output - generated by voxelizer\n";

    int vc = 0;
    long long vox = 0;
    OctreeStats stats;
    stats.init(maxDepth);

    auto startTime = chrono::high_resolution_clock::now();
    buildOctree(out, root, vertices, faces, 1, maxDepth, vc, vox, stats);
    auto endTime = chrono::high_resolution_clock::now();
    out.close();

    double elapsed = chrono::duration<double>(endTime - startTime).count();

    printReport(vox, stats, elapsed, outputPath);

    return 0;
}